apiVersion: v1
kind: Service
metadata:
  name: webkyte-antipiracy-service
  namespace: default
  labels:
    app: webkyte-antipiracy
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30007
    name: http
    protocol: TCP
  selector:
    app: webkyte-antipiracy
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
